### PR TITLE
Update semantics.md to improve consistency across example sections

### PR DESCRIPTION
**Pull request by rat10**
Keep the use of xsd:int for the forth variant consistent across different examples

### CODE REVIEW

**Comment by afs** [comment]
We should prefer `^^xsd:integer` except when we want to make a point.

In Turtle a plain `4` is an `xsd:integer`.

In XQuery/XPath, any integer-valued operation returns an `xsd:integer`so there is a first amongst equals.

**Comment by rat10** [comment]
But we do want to make a point here, and this particular datatype is just an example. Or do you suggest to use another datatype?

**Comment by pfps** [comment]
The bigger question is whether to have all the base triples be integer instead of int, and have the entailed or not-entailed triples be int.

**Comment by TallTed** [comment]
> The bigger question is whether to have all the base triples be integer instead of int, and have the entailed or not-entailed triples be int.

Have those questions been put in their own issue?  If not, please do...

**Pull request merged**
